FROM golang:1.18-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY ./internal/ ./internal/
COPY ./cmd/manager/ ./cmd/manager/

RUN go build -v -o /manager ./cmd/manager

FROM alpine:latest

COPY --from=build /manager /manager

CMD [ "./manager" ]