version: "3.9"
services:
  server:
    build: 
      context: .
      dockerfile: internal/app/server/Dockerfile
    ports: 
      - 3000:3000
    depends_on:
      - manager
  manager:
    build:
      context: .
      dockerfile: internal/app/manager/Dockerfile