version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    ports: 
      - 3000:3000
    environment:
      - MONGODB_CONNSTRING=${MONGODB_CONNSTRING:?}
      - API_TOKEN=${WEB_API_TOKEN}
    depends_on:
      - manager
  manager:
    build:
      context: .
      dockerfile: Dockerfile.manager
    environment:
      - MONGODB_CONNSTRING=${MONGODB_CONNSTRING:?}
      - MOODLE_USERNAME=${MOODLE_USERNAME:?}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD:?}
      - MOODLE_ROOT_URL=${MOODLE_ROOT_URL:?}
      - MOODLE_COURSE_ID=${MOODLE_COURSE_ID:?}