FROM golang:1.18-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY ./internal/mongodb ./internal/mongodb
COPY ./internal/schedule ./internal/schedule
COPY ./cmd/web/ ./cmd/web/

RUN go build -v -o /web ./cmd/web

FROM alpine:latest

COPY --from=build /web /web

CMD [ "./web" ]